FROM node:20-alpine
WORKDIR /app
COPY package*.json turbo.json ./
COPY packages ./packages
COPY apps/api/package.json ./apps/api/package.json
RUN npm ci --include=dev
COPY . .
RUN npm run build --workspace=@chromacommand/api
CMD ["node", "apps/api/dist/index.js"]
EXPOSE 4000
