FROM node:20-alpine
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY package*.json turbo.json ./
COPY packages ./packages
COPY apps/dashboard/package.json ./apps/dashboard/package.json
COPY apps/api/package.json ./apps/api/package.json
RUN npm ci --include=dev
COPY . .
RUN npx turbo run build
WORKDIR /app/apps/dashboard
CMD ["npm", "start"]
EXPOSE 3000
