FROM node:20-alpine
WORKDIR /app
COPY package*.json turbo.json ./
COPY packages ./packages
COPY apps/api/package.json ./apps/api/package.json
RUN npm ci --include=dev
COPY . .
WORKDIR /app/apps/api
CMD ["npx", "tsx", "src/index.ts"]
EXPOSE 4000
